cameraDistorsionParamPath: ../mbn_common/camera_calibration/spotLightCam1.cal
cameraWidth: 640
cameraHeight: 480
blackWhiteThreshold: 0
min_confidence: 0.51
enableIDfilter: true
enableDetectOnlyTheBest: false
useBCH: true
fixedCameratransform_orientation_x: -0.632428
fixedCameratransform_orientation_y: 0.632176
fixedCameratransform_orientation_z: -0.316282
fixedCameratransform_orientation_w: 0.316786
fixedCameratransform_position_x: 0.248988
fixedCameratransform_position_y: 0.0
fixedCameratransform_position_z: 0.497012
markersBaseWidth: 40
markersVectorIDtoFind: [0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
markersDimensions:     [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]

